### ISSUE TITLE
Mail list

### ISSUE THREAD

**Issue by sapegin** [ThinkingInReact/ThinkingInReact#2]
Or anything like that to know about the new content.

**Comment by sapegin** [comment]
@k2052 ping.

**Comment by k2052** [comment]
Apologies this took so long, I got sidetracked by things and had to set aside Thinking in React for a bit. Here is a mailing list: http://eepurl.com/bU3k-j. I will add a link to it on the site in a few. There will be many updates coming soon! Thanks for your support!
